### ISSUE TITLE
Kim Jong-un can cause assertion failure in OpenCV

### ISSUE THREAD

**Issue by mgeens** [jerry-git/thug-memes#3] opened 2018-03-19 18:54 UTC
I got an assertion failure the first time I tried the attached image. It doesn't fail consistently, sometimes it succeeds.

```
rgeens@ubuntu:~Downloads$ ../.local/bin/thug c2a9ddea-13ad-46aa-ac6e-29c03cc1ab7d.jpg "LOL" "LOL"
[ INFO:0] Initialize OpenCL runtime...
OpenCV Error: Assertion failed ((mtype == 0 || mtype == 1) && _mask.sameSize(*psrc1)) in binary_op, file /io/opencv/modules/core/src/arithm.cpp, line 241
Traceback (most recent call last):
  File "../.local/bin/thug", line 11, in <module>
    sys.exit(thug_meme())
  File "/home/rgeens/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/rgeens/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/rgeens/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rgeens/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/rgeens/.local/lib/python3.6/site-packages/thug/cli.py", line 115, in thug_meme
    meme.create(res_path)
  File "/home/rgeens/.local/lib/python3.6/site-packages/thug/meme/thug.py", line 31, in create
    self._draw_cigar(img, thug)  # depends also on eyes
  File "/home/rgeens/.local/lib/python3.6/site-packages/thug/meme/thug.py", line 107, in _draw_cigar
    self._draw_on_top(img, x, y, scaled_rot)
  File "/home/rgeens/.local/lib/python3.6/site-packages/thug/meme/thug.py", line 122, in _draw_on_top
    background = cv2.bitwise_and(background, background, mask=mask_inv)
cv2.error: /io/opencv/modules/core/src/arithm.cpp:241: error: (-215) (mtype == 0 || mtype == 1) && _mask.sameSize(*psrc1) in function binary_op
```

 ![c2a9ddea-13ad-46aa-ac6e-29c03cc1ab7d](https://user-images.githubusercontent.com/511604/37615904-a60b7c36-2bae-11e8-9cae-5bb275d30901.jpg).

**Comment by jerry-git** [comment] 2018-03-20 06:47
This is most likely a duplicate of #1. Inconsistency in the output is due to random angle of the cigar, I think it fails in this case if it points down since Kim's mouth is so close to image bottom. Thanks for providing the image @rgeens!

**Closed as completed** 2018-03-20 06:47 UTC
Labels: duplicate

**Comment by jerry-git** [comment] 2018-03-20 20:14
Duplicate of #1
